# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [155]:
import numpy as np
f=open('/Users/sysoevkd/Downloads/v1/data/minutes_n_ingredients.csv')
a=np.loadtxt(f,dtype=int,delimiter=',',skiprows=1,max_rows=5)
print(a)
F=np.loadtxt(f,dtype=int,delimiter=',',skiprows=1)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [156]:
print(max(F[:,1]),min(F[:,1]),)
print(max(F[:,2]),min(F[:,2]))
s1=F[:,1:3].sum(axis=0)
print(s1[0]/len(F[:,1]),s1[1]/len(F[:,2]))
sor=np.sort(F[:,1])
print(sor[len(sor)//2])
sor=np.sort(F[:,2])
print(sor[len(sor)//2])

2147483647 0
39 1
21602.295827749665 9.055263315798948
40
9


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [157]:
q=np.quantile(F[:,1],0.75)
qu=np.clip(F[:,1],0,q)
print(qu)



[18. 15.  7. ... 65.  5. 65.]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [158]:
b=np.count_nonzero(F==0)
print(b)
F[:,1][F[:,1]==0]=1
F[:,1]

479


array([ 18,  15,   7, ...,  65,   5, 140])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [163]:
print((np.unique(F[:, 1:3]).shape[0]))

655


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [165]:
K=0
new = np.array([])
for k in F[:,2]:
    c=np.count_nonzero(F[:,2]==k)
    if c==1:
        new=np.append(new,k)
        K=K+1

print(new,K)

[39. 37. 32. 34.] 4


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [154]:
ver=F[F[:,1]<=5]
ver

array([[204134,      5,      3],
       [ 66842,      2,      4],
       [140245,      5,      5],
       ...,
       [420725,      5,      3],
       [  4747,      1,      9],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [166]:
F1=F.copy()
F1=np.array(F[:,2]/F[:,1])
F1
print(max(F1))

24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [167]:
import pandas as pd
df=pd.DataFrame(F)
su=0
dfs=df.sort_values(by=1,ascending=False)
for i in dfs[:100][2]:
    su=su+i
suu=su/len(dfs[:100][2])
suu

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах


In [ ]:
r=np.random.choice(F.shape[0],10)

print(F[r])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [144]:
F2=F[:,2].copy()
FR=F2[F2<suu]
Pr=len(FR)/len(F2)*100
Pr


26.637598255895355

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [150]:
FP=F.copy()
FP=np.c_[FP,(F[:,1]<20) & (F[:,2]<5)]
FP

array([[ 33941,     18,      9,      0],
       [446597,     15,      5,      0],
       [366174,      7,      9,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [153]:
FP[FP[:,3]==1].shape[0]/FP.shape[0]*100

5.0933055983359

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.